import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "niji_app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className='bg-gray-900 mx-40'
      >
        <div className="bg-black text-white">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
