import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import NavTabs from '@/components/NavTabs';

export const metadata: Metadata = {
  title: "VtubeTracker",
  description: "Generated by create next app",
  icons: {
    icon: "/tabIcon.png", // パスは public ディレクトリ基準
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className='bg-gray-900 lg:mx-50'
      >
        <div className="bg-black text-white">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
